### PR TITLE
add leading zeros for constant line length in log file

### PR DESCRIPTION
**Pull request by ikstream**
Signed-off-by: Stefan Venz <stefan.venz@protonmail.com>

### CODE REVIEW

**Comment by nadim-el-sayed** [comment]
@ikstream Great Job!, we could also consider padding the Voltage and Frequency.

**Comment by thuehn** [comment]
+1 for padding all values & please proide a sample output line before and after the patch.

**Comment by ikstream** [comment]
Output line before patch:
DEV_UUID,1457725785,1457725785712,3,227.307770,50.018005,1.325596,1.263674,1.863896,1.092294,0.949149,0.857004,1.470840

Output line after the patch:
DEV_UUID,1457725424,1457725424488,3,226.626389,50.026588,01.318179,01.166306,01.867398,01.334225,00.799908,00.750853,02.068761

**Comment by ikstream** [comment]
@nadim-el-sayed how many digits before the decimal point should the frequency/voltage be padded to?

**Comment by thuehn** [comment]
Voltage needs 3 decimal places (Voltage from 0V .. 250V) and frequency needs 2 decimal places (0Hz .. 51Hz).

**Comment by nadim-el-sayed** [comment]
Not sure if it's right. When you put %0nd means - AFAIK - that the overall digits will be n and the rest will be zero padded. We need to make sure that the %03.6f still does the zero padding, considering the "." plus the six digits after the "." make already 7.

**Comment by ikstream** [comment]
Thats true, it needs to be %010.6f and %09.6f

**Comment by thuehn** [comment]
As I have already merged the previous patch, please put the new changes as seperate pr.

**Pull request merged**
