### PR TITLE
[RFC] Round Robin log file write

### PR DESCRIPTION
**Pull request by ikstream**
If the powquty log file hits max size we want to be able to write new entries from the first line
of the file. In addition, if powqutyd crasches, we want to be able to continue writing from last position. This pr introduces both functionalities.

is max file size reached?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;->no: just append
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;->yes: has this been checked already?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;->yes: write to current offset
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;->no: is the first line the oldest line?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-> yes: write to first line
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-> no: go to offset in file after latest write

As logarithmic search is used, large files are parsed efficiently as well.
The position in the file is calculated by the offset of a line and the line parsed for its timestamp entry.

If the timestamp of the first line is older(smaller) as the timestamp of the last line we will resume writing from first line.
If powqutyd crashed, the timestamp of the first and last line will be compared. Depending on its values the interval is halved in each iteration and the boundaries for the search set accordingly until the latest(biggest) value is found.

### CODE REVIEW

**Comment by thuehn** [comment]
Looks good to me. Nadim, comments ?

**Comment by nadim-el-sayed** [comment]
@ikstream: looks very good :+1: i will review the code and test it before merging.

**Comment by nadim-el-sayed** [comment]
While testing, i came across the following problem (see below) investigating ....

nadim@nadim-ThinkPad-T520:/media/nadim/data1/src/thuehn/powquty/powqutyd/files$ sudo ./powqutyd 
looking up dev_uuid: currently ==> BERTUB002
looking up mqtt_host: currently ==> localhost
looking up mqtt_topic: currently ==> devices/update
looking up device_tty currently ==> /dev/ttyACM3
UCI CONFIG FTW!!!Starting powqutyd ...
dev_uuid: BERTUB002
powqutyd_print: 1
MQTT Thread started 
conf device_tty ==> /dev/ttyACM3
config device_tty ==> /dev/ttyACM3
Offset: -25.910156	Scaling: 0.012355
Retrieval Thread started 
Calculation Thread started
BERTUB002,1486641173462,1,0.1,0.1,029
Segmentation fault (core dumped)
nadim@nadim-ThinkPad-T520:/media/nadim/data1/src/thuehn/powquty/powqutyd/files$ sudo gdb ./powqutyd 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./powqutyd...done.
(gdb) run
Starting program: /media/nadim/data1/src/thuehn/powquty/powqutyd/files/powqutyd 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
looking up dev_uuid: currently ==> BERTUB002
looking up mqtt_host: currently ==> localhost
looking up mqtt_topic: currently ==> devices/update
looking up device_tty currently ==> /dev/ttyACM3
UCI CONFIG FTW!!!Starting powqutyd ...
dev_uuid: BERTUB002
powqutyd_print: 1
[New Thread 0x7ffff5fed700 (LWP 11717)]
MQTT Thread started 
conf device_tty ==> /dev/ttyACM3
config device_tty ==> /dev/ttyACM3
[New Thread 0x7ffff57ec700 (LWP 11718)]
Offset: -25.910156	Scaling: 0.012355
Retrieval Thread started 
[New Thread 0x7ffff4dd9700 (LWP 11719)]
Calculation Thread started
BERTUB002,1486641182515,1,0.1,0.1,029

Thread 4 "powqutyd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4dd9700 (LWP 11719)]
__GI_____strtol_l_internal (nptr=0x0, endptr=endptr@entry=0x0, base=base@entry=10, group=group@entry=0, loc=0x7ffff7286420 <_nl_global_locale>)
    at ../stdlib/strtol_l.c:293
293	../stdlib/strtol_l.c: No such file or directory.
(gdb) bt
#0  __GI_____strtol_l_internal (nptr=0x0, endptr=endptr@entry=0x0, base=base@entry=10, group=group@entry=0, loc=0x7ffff7286420 <_nl_global_locale>)
    at ../stdlib/strtol_l.c:293
#1  0x00007ffff6efd3d2 in __strtol (nptr=<optimized out>, endptr=endptr@entry=0x0, base=base@entry=10) at ../stdlib/strtol.c:106
#2  0x00007ffff6ef8e90 in atoi (nptr=<optimized out>) at atoi.c:27
#3  0x000000000040229d in get_line_entry (file=0x7fffe80008c0) at src/helper.c:231
#4  0x00000000004023be in set_position (file=0x7fffe80008c0, u_bound=0, l_bound=6858, char_count=127) at src/helper.c:261
#5  0x0000000000402411 in set_position (file=0x7fffe80008c0, u_bound=0, l_bound=13716, char_count=127) at src/helper.c:266
#6  0x0000000000402411 in set_position (file=0x7fffe80008c0, u_bound=0, l_bound=27559, char_count=127) at src/helper.c:266
#7  0x000000000040257a in store_to_file (pqResult=..., powquty_path=0x7fffffffe400 "/tmp/powquty.log") at src/helper.c:294
#8  0x0000000000403d45 in calculation_thread_run (param=0x0) at src/calculation.c:144
#9  0x00007ffff72926ba in start_thread (arg=0x7ffff4dd9700) at pthread_create.c:333
#10 0x00007ffff6fc882d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by ikstream** [comment]
As `get_curr_time_in_seconds()`  returns an int (`return (int) (tv.tv_sec);`) we do not need to use long for the time_value in the comparison for the bounds(lower/upper/mid).

Should this be used as long instead?

**Comment by nadim-el-sayed** [comment]
Let's change it and use long int instead. This will be useful when dealing with millisecond timestamps

**Comment by nadim-el-sayed** [comment]
@ikstream Thanks :+1:

**Pull request merged**
