### PR TITLE
(l)uci max log size

### PR DESCRIPTION
**Pull request by ikstream**
Enable the user to configure the maximum log size.
This can be done in the config file or in the web interface.

### CODE REVIEW

**Comment by thuehn** [comment]
thx & merged

**Comment by nadim-el-sayed** [comment]
@ikstream: if you use store_to_file(..., config) the file storage functionality cannot be used flexibly for generating log and raw data!

**Comment by ikstream** [comment]
I see your point, but i think the bigger issue is the pqresult as the first parameter for store_to_file().

**Comment by nadim-el-sayed** [comment]
True. This is why we should think of making the csv_rrd functionality kind of independent. In that case the store_to_file takes only the csv string to store. and the caller have to make sure that the string length is consistent.
IMHO this is a very good functionality that can be reused in many other contexts. your own new libstoffel

**Pull request merged**
